
name: Deploy Pathfidner monitor to GitHub Pages

on:
  push:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          persist-credentials: false # otherwise, the token used is the GITHUB_TOKEN, instead of your personal token
          fetch-depth: 0 # otherwise, you will failed to push refs to dest repo
          ref: master
      - uses: actions/setup-node@v1
        with:
          node-version: 12
      # local changes
      - run: yarn --frozen-lockfile
      - name: Install dependencies 
        run: yarn install
      - name: Create new build
        run: yarn run build
      - name: Remove legacy build
        run: rm -rf docs
      - name: Copy new build to target library
        run: cp -rf build docs
        env:
          CI: false
      - name: Add files to git
        run: git add --all
      # setting up git
      - name: Config user email
        run: git config --local user.email "action@github.com"
      - name: Config user name
        run: git config --local user.name "GitHub Action"
      - name: Commit changes
        run: git commit -a -m "docs-deploy-gh-pages deployed docs."
      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: build
          force: true 
