# This workflow runs automated tests on pull requests and releases.
name: pathfinder-monitor-run-tests

on:
  release:
    types: [created]
  pull_request:
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 12
      - run: yarn --frozen-lockfile
      - run: yarn install
      - run: yarn run test